# Generated by Django 4.2.6 on 2023-11-28 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myaddress",
            name="address_name",
        ),
        migrations.RemoveField(
            model_name="weight",
            name="sport_name",
        ),
        migrations.AddField(
            model_name="myaddress",
            name="address",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gym",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="sports.gym"
            ),
        ),
        migrations.AddField(
            model_name="weight",
            name="sport",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.sport",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="myaddress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="GymAddress",
        ),
    ]
