# Generated by Django 4.2.6 on 2023-11-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_myaddress_address_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weight",
            name="name",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
