# Generated by Django 4.2.6 on 2023-11-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_weight_max_weight_alter_weight_min_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weight",
            name="max_weight",
        ),
        migrations.AlterField(
            model_name="weight",
            name="min_weight",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
