# Generated by Django 4.2.6 on 2023-11-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_weight"),
        ("users", "0006_remove_weight_max_weight_alter_weight_min_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.weight",
            ),
        ),
        migrations.DeleteModel(
            name="Weight",
        ),
    ]
