# Generated by Django 4.2.6 on 2023-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_weight_delete_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="years",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
