# Generated by Django 4.2.6 on 2023-12-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_years"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kakao_id",
        ),
    ]
