# Generated by Django 4.2.6 on 2023-12-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_user_kakao_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyAddress",
            new_name="Location",
        ),
    ]
