# Generated by Django 4.2.6 on 2023-12-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_myaddress_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="years",
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
