# Generated by Django 4.2.6 on 2023-12-03 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412,
                        message="한글, 소문자, 숫자만 가능, 5-15자",
                        regex="^[가-힣a-z0-9]{3,15}$",
                    )
                ],
            ),
        ),
    ]
