# Generated by Django 4.2.6 on 2023-12-06 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0005_alter_gym_address_alter_gym_latitude_and_more"),
        ("users", "0012_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(help_text="도로명주소 또는 지번주소", max_length=50),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.IntegerField(help_text="위도"),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.IntegerField(help_text="경도"),
        ),
        migrations.AlterField(
            model_name="location",
            name="user",
            field=models.OneToOneField(
                help_text="사용자아이디",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(
                help_text="연령",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412, message="10, 20, 30 가능", regex="^[1-3]{1}[0]{1}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="메일주소", max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                help_text="성별",
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412, message="M 또는 F, (male or female)", regex="^[MF]{1}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gym",
            field=models.ForeignKey(
                default=1,
                help_text="체육관아이디",
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.gym",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, help_text="유저 상태(활성화 여부)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="닉네임",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412,
                        message="한글, 소문자, 숫자만 가능, 5-15자",
                        regex="^[가-힣a-z0-9]{3,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.ForeignKey(
                default=1,
                help_text="체급아이디",
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.weight",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="years",
            field=models.PositiveIntegerField(
                help_text="스포츠경력",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="yellow_card",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="유효신고횟수"
            ),
        ),
    ]
