# Generated by Django 4.2.6 on 2023-12-29 21:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_location_address_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="current_location",
            field=models.ForeignKey(
                default=1,
                help_text="위치아이디",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.location",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(
                help_text="연령, 10, 20, 30",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412, message="10, 20, 30 가능", regex="^[1-3]{1}[0]{1}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                help_text="성별 M(남), F(여)",
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412, message="M 또는 F, (male or female)", regex="^[MF]{1}$"
                    )
                ],
            ),
        ),
    ]
