# Generated by Django 4.2.6 on 2023-12-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_location_user_user_current_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_location",
            field=models.ForeignKey(
                help_text="위치아이디",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.location",
                unique=True,
            ),
        ),
    ]
