# Generated by Django 4.2.6 on 2023-12-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_current_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(help_text="위도"),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(help_text="경도"),
        ),
    ]
