# Generated by Django 4.2.6 on 2024-01-07 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0006_alter_gym_latitude_alter_gym_longitude"),
        ("users", "0016_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sport",
            field=models.ForeignKey(
                default=1,
                help_text="종목아이디",
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.sport",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="닉네임(한글, 소문자, 숫자만 가능, 3-15자)",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412,
                        message="한글, 소문자, 숫자만 가능, 3-15자",
                        regex="^[가-힣a-z0-9]{3,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="years",
            field=models.PositiveIntegerField(
                help_text="스포츠경력(1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
