# Generated by Django 4.2.6 on 2024-01-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0006_alter_gym_latitude_alter_gym_longitude"),
        ("users", "0017_user_sport_alter_user_username_alter_user_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gym",
            field=models.ForeignKey(
                help_text="체육관아이디",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="sports.gym",
            ),
        ),
    ]
