# Generated by Django 4.2.6 on 2024-01-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_user_gym"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="current_location",
        ),
    ]
