# Generated by Django 4.2.6 on 2024-01-08 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_user_current_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="user",
            field=models.OneToOneField(
                help_text="유저pk",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_location",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
