# Generated by Django 4.2.6 on 2024-01-08 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_location_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="user",
            field=models.OneToOneField(
                default=1,
                help_text="유저pk",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_location",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
