# Generated by Django 4.2.6 on 2024-01-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_location_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="UserLocation",
        ),
    ]
