# Generated by Django 4.2.6 on 2024-01-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_rename_location_userlocation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserLocation",
            new_name="Location",
        ),
    ]
