# Generated by Django 4.2.6 on 2024-02-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_banneduser_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accuse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=500)),
                (
                    "reported_user",
                    models.ForeignKey(
                        help_text="신고당한자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="신고자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuse_reporter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
