# Generated by Django 4.2.6 on 2024-02-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_accuse"),
    ]

    operations = [
        migrations.AddField(
            model_name="accuse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="작성일", null=True),
        ),
    ]
