# Generated by Django 4.2.6 on 2024-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_accuse_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="accuse",
            name="admin_confirm",
            field=models.BooleanField(blank=True, default=False, help_text="관리자 확인 여부"),
        ),
    ]
