# Generated by Django 4.2.6 on 2023-11-29 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0002_alter_sport_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator(
                                code=412,
                                message="M 또는 F, (male or female)",
                                regex="^[MF]{1}$",
                            )
                        ],
                    ),
                ),
                ("min_weight", models.PositiveIntegerField()),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sports.sport"
                    ),
                ),
            ],
        ),
    ]
