# Generated by Django 4.2.6 on 2023-12-02 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weight",
            name="gender",
            field=models.CharField(
                help_text="남성 M, 여성 F",
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        code=412, message="M 또는 F, (male or female)", regex="^[MF]{1}$"
                    )
                ],
            ),
        ),
    ]
