# Generated by Django 4.2.6 on 2023-12-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0004_alter_weight_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="address",
            field=models.CharField(help_text="도로명주소 또는 지번주소", max_length=50),
        ),
        migrations.AlterField(
            model_name="gym",
            name="latitude",
            field=models.IntegerField(help_text="위도"),
        ),
        migrations.AlterField(
            model_name="gym",
            name="longitude",
            field=models.IntegerField(help_text="경도"),
        ),
        migrations.AlterField(
            model_name="gym",
            name="name",
            field=models.CharField(help_text="체육관이름", max_length=15),
        ),
        migrations.AlterField(
            model_name="gym",
            name="sport",
            field=models.ForeignKey(
                help_text="종목아이디",
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.sport",
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(help_text="스포츠명", max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="weight",
            name="min_weight",
            field=models.PositiveIntegerField(help_text="해당몸무게(kg) 이상"),
        ),
        migrations.AlterField(
            model_name="weight",
            name="name",
            field=models.CharField(help_text="체급명", max_length=15),
        ),
        migrations.AlterField(
            model_name="weight",
            name="sport",
            field=models.ForeignKey(
                help_text="종목아이디",
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.sport",
            ),
        ),
    ]
