# Generated by Django 4.2.6 on 2024-02-12 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="게시글 본문", max_length=500)),
                ("receiver_read", models.BooleanField(blank=True, default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="작성일", null=True),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="받는사람",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="보낸사람",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
