# Generated by Django 4.2.6 on 2024-02-12 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="게시글 본문", max_length=500)),
                (
                    "talker1",
                    models.ForeignKey(
                        blank=True,
                        help_text="참가자1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_talker1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "talker2",
                    models.ForeignKey(
                        help_text="참가자2",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_talker2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="보낸사람",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatroom",
                to="chats.chatroom",
            ),
            preserve_default=False,
        ),
    ]
