# Generated by Django 4.2.6 on 2024-02-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_chatroom_message_chat_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="content",
        ),
    ]
