# Generated by Django 4.2.6 on 2024-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_remove_chatroom_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="작성일", null=True),
        ),
    ]
