# Generated by Django 4.2.6 on 2024-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_chatroom_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="talker1_unread_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="talker2_unread_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
