# Generated by Django 4.2.6 on 2024-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_chatroom_talker1_unread_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="updated_at",
            field=models.DateTimeField(blank=True, help_text="작성일", null=True),
        ),
    ]
