# Generated by Django 4.2.6 on 2024-02-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sports", "0006_alter_gym_latitude_alter_gym_longitude"),
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="종목id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_category",
                to="sports.sport",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="writer",
            field=models.ForeignKey(
                blank=True,
                help_text="작성자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_writer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
