# Generated by Django 4.2.6 on 2024-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_post_category_alter_post_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0, help_text="좋아요 수"),
        ),
    ]
