# Generated by Django 4.2.6 on 2024-02-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_post_like_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="업데이트일", null=True),
        ),
        migrations.AddField(
            model_name="reply",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="업데이트일", null=True),
        ),
    ]
