# Generated by Django 4.2.6 on 2024-02-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_remove_post_created_at_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                help_text="게시글 id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="boards.post",
            ),
        ),
    ]
